### ISSUE TITLE
Convert all HTTP URIS to HTTPS

### ISSUE THREAD

**Issue by davidamichelson** [VandyVRC/srophe-eXist-app#110]
@wsalesky It looks like there is a bug in the system. The content negotiation expects HTTPS for bibl URIS: https://architecturasinica.org/bibl/IMF7GRAI

But the copy and paste URI on that page is HTTP: not HTTPS

We have tried to cite this bibl in record: https://architecturasinica.org/place/000001 but it is not populating correctly. Can you check?

Also this same HTTP and HTTPS seems to apply to place and keyword records as well, so this may be two issues?

**Comment by davidamichelson** [comment]
So when we cite URIS in the TEI should they be HTTP or HTTPS?

**Comment by davidamichelson** [comment]
Just to clarify at the bottom of the HTML for https://architecturasinica.org/place/000001 it is not auto populating the footnote from the bibl record as expected.

**Comment by davidamichelson** [comment]
Also the HTML for https://architecturasinica.org/place/000001 is not inserting a footnote.

**Comment by wsalesky** [comment]
Originally I had them as HTTPS but the rest of the TEI uses HTTP, so I changed the bibl module. We could do a find and replace on the old data and go forward with HTTPS? I'm fine with either, but need them to be consistent.

**Comment by davidamichelson** [comment]
@wsalesky Thanks, so I think this needs to be split into two issues. This issue #110 here can be fore Convert all HTTP URIS to HTTPS. Would you please run a find and replace on the app and the data for architecturasinica?

**Comment by wsalesky** [comment]
@davidamichelson  @millertg 
Done. Please make sure to pull the updated data before doing any editing.
