### ISSUE TITLE
Footnote Data in HTML is not Populating based on the Bibl URI

### ISSUE THREAD

**Issue by davidamichelson** [VandyVRC/srophe-eXist-app#111]
This issue was split off of #110 

In the record:  https://architecturasinica.org/place/000001 there is a bibl with a valid URI (https://architecturasinica.org/bibl/IMF7GRAI) but in the HTML rendering of https://architecturasinica.org/place/000001 the footnote is not pulling the Author/Title information from the bibl record (https://architecturasinica.org/bibl/IMF7GRAI) and so the footnote is malformed:

```1 , pp: III:762;57-C1.```

**Comment by wsalesky** [comment]
@davidamichelson @millertg This is fixed.
