### ISSUE TITLE
update index.html

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#119]
@wsalesky I tried to update the homepage, but it doesn't seem to load. https://github.com/VandyVRC/srophe-eXist-app/blob/master/index.html
lines 12-21. 
What am I doing wrong?

**Comment by wsalesky** [comment]
@millertg You can always check the webhooks to see why your commit failed. In this case, the server timed out the request. I don't know why. However I reran the commit and it is now online.

**Comment by millertg** [comment]
I can?

**Comment by wsalesky** [comment]
I will email instructions tomorrow

**Comment by millertg** [comment]
Thanks, Winona. Whenever you get to it. I really appreciate your patient instruction. 

Sample footnote to come.
