### ISSUE TITLE
modify logos on about page

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#121]
@winona 
I added images of logos for our Chinese university sponsors, but I can't seem to size them properly. Can you help/tell me how to resize, and move them to the bottom of the page?

**Comment by millertg** [comment]
@wsalesky 
Or it may be that the site is not updating. I tried to delete one of the images

**Comment by wsalesky** [comment]
@millertg You can add a height or width attribute to the image tag: 
https://github.com/VandyVRC/srophe-eXist-app/blob/master/about.html#L45

**Comment by wsalesky** [comment]
@millertg Checking in. Did you get this fixed or do you still need help?

**Comment by millertg** [comment]
My internet access on my computer is down. Gotta love China. If you could help with this that would be so wonderful.
Thanks-
Tracy

tm

Sent from my iPhone

On May 29, 2019, at 12:09 AM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


@millertg<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmillertg&data=02%7C01%7Ctracy.g.miller%40vanderbilt.edu%7C7de84963649f4705397308d6e386e6a7%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636946565866576372&sdata=6Pd%2B2oii0cOOvAcD5AIwh4LhsgggNHSbekNMnSTsyW8%3D&reserved=0> Checking in. Did you get this fixed or do you still need help?

**Comment by millertg** [comment]
@wsalesky 
I have it up, and it seemed to work once, but later changes didn't take. Cleared browsing data, but I am not seeing smaller images.
Also--how can I move this to the bottom of the page?

**Comment by wsalesky** [comment]
I will get the most recent changes up. Do you want all the sponsors at the bottom of the page or just the new ones?

**Comment by millertg** [comment]
Thank you. I think all of them would be best. Would you mind putting them on the bottom of the home page as well?

Thanks a million!

tm

Sent from my iPhone

On May 29, 2019, at 8:28 AM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


I will get the most recent changes up. Do you want all the sponsors at the bottom of the page or just the new ones?

**Comment by wsalesky** [comment]
@millertg I have updated them, how do they look now? I can make changes if you want them styled differently.

**Comment by millertg** [comment]
They look great. I only worry that they are too far away from the main body. I fear people won’t scroll down. Maybe I should change the photo on the about page to one with a horizontal orientation.
Thanks
tm

Sent from my iPhone

On May 29, 2019, at 9:31 PM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


@millertg<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmillertg&data=02%7C01%7Ctracy.g.miller%40vanderbilt.edu%7C5c1044086ac547913ff308d6e439ee78%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636947334794610555&sdata=rIj2P2W%2BCmn4UJUGvWCqOY%2ByYj577Db%2B3orMeQYoRoI%3D&reserved=0> I have updated them, how do they look now? I can make changes if you want them styled differently.

**Comment by wsalesky** [comment]
@millertg Okay. I think this issue is resolved. Let me know if you want help making any other changes.
