### ISSUE TITLE
more/less button displays more only when less is clicked

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#122]
@wsalesky 
On the architectural terminology page: 
https://architecturasinica.org/terminology.html
The more/less button--a great feature, but it doesn't show more when you click more, it only shows more when you then click less.

**Comment by wsalesky** [comment]
Fixed. Some of the other JavaScript on the page was interfering with the more/less toggle function.

**Comment by millertg** [comment]
Thank you!

tm

Sent from my iPhone

On May 27, 2019, at 3:06 AM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed. Some of the other JavaScript on the page was interfering with the more/less toggle function.
