### ISSUE TITLE
show latest modification in "How to Cite this Entry" footer

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#127]
@wsalesky 
I am trying to remember to add a date to any revision to the TEI that goes beyond fixing typos using <revisionDesc>. You can see this in the one I worked on most recently: https://github.com/VandyVRC/tcadrt/blob/master/data/keywords/tei/k000011.xml#L58. But I don’t see the updated date under “How to Cite This Entry” at the bottom of the page. Would it be possible to have the date displayed in the short citation reflect the latest substantial update?

screenshot of https://architecturasinica.org/keyword/k000011:
<img width="840" alt="Screen Shot 2020-06-08 at 8 43 05 AM" src="https://user-images.githubusercontent.com/25234059/84100876-60c57100-a9d2-11ea-9556-00341eba1d22.png">

**Comment by wsalesky** [comment]
Fixed.
