### ISSUE TITLE
Change in displaying entry author in citation

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#128]
@wsalesky 
For the "Bibliography" in citation information, can we display the individual/group responsible for initial research as the author? 

So in https://architecturasinica.org/keyword/k000005
The citation is: 
![image](https://user-images.githubusercontent.com/25234059/84182756-82fdd400-aa50-11ea-9b08-e8f1cbd9bfce.png)

But it would be better to identify the contributing author as the entry author. We are tagging the contributors under "initial research," could we change this to: 

![image](https://user-images.githubusercontent.com/25234059/84182982-da03a900-aa50-11ea-8353-a5f8ebede099.png)

**Comment by wsalesky** [comment]
Done.
