### ISSUE TITLE
place/building to artifact(s)

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#132]
We want to homogenize the display of links in the "contains" section to display the word "artifact(s)" instead of both "buildings" and "places"

Concern:  
@wsalesky 
In the places folder for the Dynamic Site Archive the term for the "contains" reference link is different for different pages. 

Solution request: 
We think that the single term "artifact(s)" would work better for everything, as it will also allow us to develop separate pages for historic sculpture, stele inscriptions, etc.

For example, Anchansi: 
On the landing page for the DSA we see: 
Name of Site (contains 1 buildings)
https://architecturasinica.org/research-tool.html
![Screen Shot 2020-06-18 at 11 41 33 AM](https://user-images.githubusercontent.com/25234059/85048294-c0511880-b158-11ea-9c54-372d65994118.png)

On the landing page for the site Anchansi we see: 
Contains Place (1)
https://architecturasinica.org/place/000001
![Screen Shot 2020-06-18 at 11 46 41 AM](https://user-images.githubusercontent.com/25234059/85048755-643ac400-b159-11ea-9518-c095d2142a43.png)

**Comment by wsalesky** [comment]
Fixed.
