### ISSUE TITLE
location of <note type="Annotation">

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#133]
@wsalesky 
My colleagues in Nanjing would like to use @type "Annotation" for the longer description, but I have moved away from it because it seems to be appearing in alphabetical order, above other types of notes (e.g. Scope Notes, Notes, Note (brief), Note (full), etc.). Can we change this so that Annotation appears in the position it appears in the TEI? That is, underneath the Scope Note? 
See, in particular https://architecturasinica.org/keyword/k000013.

Thanks!!

**Comment by wsalesky** [comment]
Fixed. Removed sorting on label. Should appear in the order they are listed in TEI.
