### ISSUE TITLE
tsv output doesn't include more than two otherNote fields

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#136]
@wsalesky 
![image](https://user-images.githubusercontent.com/25234059/89553335-02025500-d7d3-11ea-9a6a-39547ee57fb3.png)

![Screen Shot 2020-08-06 at 10 51 23 AM](https://user-images.githubusercontent.com/25234059/89553171-ce272f80-d7d2-11ea-8d96-573a8685009d.png)

**Comment by wsalesky** [comment]
@millertg The disadvantage to TSV is that it is fixed fields, so I can add more notes but I would need to know how many. Do you have a maximum number? Also, I can add the names if I know ahead of time what they are. Do you have a list? If not I can generate a list of note names. Does each note type have only one note? If more than one note for each type what would you guess is the maximum #? 
Thanks!

**Comment by millertg** [comment]
each type has only one note, but within each note are multiple languages, marked with the appropriate language element. Would it be possible to have the languages separated out as well? that is: noteBriefEn, noteBriefzh-HanT, etc.?

**Comment by wsalesky** [comment]
@millertg Yes, I can make that happen. Will let you know when it is ready.

**Comment by millertg** [comment]
Thanks!
one more thing: <note type="related concepts"> will have multiples, maybe as many as 10

**Comment by millertg** [comment]
I mean: one more thing: <note type="related concept"> will have multiples, maybe as many as 10

**Comment by wsalesky** [comment]
@millertg Sorry for the delay. Can you take a look at the new format and tell me if I have caught everything? Let me know if I missed any note types? Thanks!

**Comment by millertg** [comment]
@wsalesky  I think that is all of the note columns (and more :-)). A few questions--see https://architecturasinica.org/keyword/k000005.tei--for an example.
1. Why does noteBrief-en also include zh-hant text? That is- can I tag another language without adding another note element?
2. for the notes in Chinese text, we are only using zh-hant (traditional characters), can we have that, not zh-hans
3. can I have a column for an elements in the responsibility statement? I would like to be able to pull out all of the records tagged ATTCAT
![Screen Shot 2020-08-13 at 1 35 20 PM](https://user-images.githubusercontent.com/25234059/90173346-f16d5400-dd69-11ea-9e46-cf28dab08aa3.png)
Thank you!!!

**Comment by millertg** [comment]
maybe a column for name type=team?

**Comment by wsalesky** [comment]
@millertg 
1. I miss interpreted how the language on the note elements worked.  I did not realize they were multiple languages in the same note. I will have to fix that so each outputs as a separate note field. 
2. Yes, I will make that change. 
3. Yes, I will make that change as will. 

Look for updates tomorrow.

**Comment by wsalesky** [comment]
@millertg How about now?

**Comment by millertg** [comment]
@wsalesky I get the English text, but not the part tagged zh-hant

**Comment by millertg** [comment]
uniquely, I do see separated text for the output on: https://architecturasinica.org/keyword/k000113
![Screen Shot 2020-08-14 at 4 27 16 PM](https://user-images.githubusercontent.com/25234059/90294021-0f5eb580-de4b-11ea-9802-662212c44cdc.png)

**Comment by wsalesky** [comment]
@millertg okay, I will take another look.

**Comment by millertg** [comment]
Just tested by changing the to lowercase h in the note field on https://architecturasinica.org/keyword/k000011 and it worked. 
We tried to follow the formatting used under "term", which has an uppercase Hant, but obviously mistakes were made. Would it be better to make the search non-case sensitive? Or should I work to homogenize the attribute?

**Comment by wsalesky** [comment]
@millertg it would be best if they were standardized one way or another. Just let me know what variation you use.

**Comment by millertg** [comment]
@wsalesky Most of them were with the uppercase H, so can we go with zh-Hant and zh-Hans across the board?

**Comment by wsalesky** [comment]
@millertg Yes, I will adjust the code.

**Comment by millertg** [comment]
@wsalesky Thank you! I will adjust my entries.

**Comment by wsalesky** [comment]
@millertg I'm fixing this today. Can you clarify, do you need notes with both lang = 'zh-Hant' and lang = 'zh-Hans', the current version only has 'zh-Hant' but I can add 'zh-Hans' if needed.

**Comment by millertg** [comment]
@wsalesky at present, we only have notes in 'zh-Hant'. zh-Hans should only be a 'term' option.
Thanks!!

**Comment by wsalesky** [comment]
@millertg great! That make my life easier! Please try the updated code and tell me if it gives you everything you need.

**Comment by millertg** [comment]
@wsalesky ok, I see one more (sorry!). We need a column for the english literal translation. It is tagged: 
term xml:lang="en" type="literal_translation"
Thanks, again!

**Comment by wsalesky** [comment]
@millertg another note?

**Comment by millertg** [comment]
@wsalesky no, a second english term. Right now it is appearing as the first 'term-other', but it is mixed with different 'others'. We should have a literal English translation for each term (still working on it, so pulling that out would be really helpful).

**Comment by wsalesky** [comment]
@millertg please test the new addition. Thanks

**Comment by millertg** [comment]
@wsalesky It looks like it is working! Thank you! I think we can close this issue.
