### ISSUE TITLE
irregular display of Wade-Giles

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#139]
@wsalesky 
@shubenda 
<language ident="zh-latn-wadegile">Wade-Giles</language>

<term xml:id="term-feature_name-5" xml:lang="zh-latn-wadegile">ts'ao</term> 
Currently displays: 
 ts'ao (zh-latn-wadegile)

To be consistent with all other languages, it should  display as:
ts'ao (Wade-Giles)
see: https://architecturasinica.org/keyword/k000005

**Comment by wsalesky** [comment]
@millertg This seems to be displaying as expected? 
<img width="236" alt="Screen Shot 2020-09-17 at 8 44 50 AM" src="https://user-images.githubusercontent.com/1168206/93472044-2701e180-f8c2-11ea-8683-ef16153b8ae0.png">

**Comment by millertg** [comment]
@wsalesky Yes! Thank you

**Comment by shubenda** [comment]
@wsalesky
@millertg 
this doesn't appear to be fixed.
we definite WG as this: <language ident="zh-latn-wadegile">Wade-Giles</language>
shouldn't the TEI be: 
<term xml:id="term-feature_name-5" xml:lang="zh-latn-wadegile">ts'ao</term>
not:
<term xml:id="term-feature_name-5" xml:lang="Wade-Giles">ts'ao</term>
please see e.g. 
https://architecturasinica.org/place/000100
it was coded consistently with other lang, but it was displayed as
Hsiao-chang-ts'un Pi-yün-ssu (**zh-latn-wadegile**)

**Comment by wsalesky** [comment]
@shubenda @millertg 
I see the problem. There are at least two encodings for Wade-Giles: 

This one (causes the poor display):
`<placeName xml:id="name000100-3" type="site-name" xml:lang="zh-latn-wadegile">Hsiao-chang-ts'un Pi-yün-ssu</placeName>`

and this one (correct display):
`<term xml:id="term-feature_name-5" xml:lang="Wade-Giles">ts'ao</term>`

Do you want me to code for both options? Or do you want to change the data? If so, which will you use?
Thanks!

**Comment by shubenda** [comment]
We will change the data.

To be consistent how other languages were coded, e will go with this one (The one caused the poor display):
<placeName xml:id="name000100-3" type="site-name" xml:lang="zh-latn-wadegile">Hsiao-chang-ts'un Pi-yün-ssu</placeName>

Thank you, Winona!

Yuh-Fen
________________________________

**Comment by wsalesky** [comment]
Fixed
