### ISSUE TITLE
pinyin no longer displaying on keyword (terminology) pages

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#140]
@wsalesky 
I just noticed that the pinyin is no longer showing next to the Chinese text with the term titles. It should display with Chinese characters *and* pinyin.
<img width="788" alt="Screen Shot 2020-09-18 at 9 27 14 PM" src="https://user-images.githubusercontent.com/25234059/93657202-29fdee80-f9f6-11ea-8958-f6fd52a37f62.png">
Thanks!

**Comment by wsalesky** [comment]
Fixed
