### ISSUE TITLE
tsv for buildings and sites

### ISSUE THREAD

**Issue by wsalesky** [VandyVRC/srophe-eXist-app#142]

**Comment by wsalesky** [comment]
@millertg This is ready for testing, just swap in 'buildings' or 'sites' for the collection parameter, rather then 'keywords'

**Comment by millertg** [comment]
@wsalesky Can we have more "building-name-other"? We need up to 10.

**Comment by wsalesky** [comment]
@millertg just for buildings? Or buildings and sites?

**Comment by millertg** [comment]
@wsalesky For both, just to be safe. The large numbers are to accommodate different linguistic representations of each alternative name.

**Comment by wsalesky** [comment]
@millertg this has been updated. Let me know if you need anything else.
