### ISSUE TITLE
500 tomcat error

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#144]
@wsalesky we were working with the dates of Anchansi https://architecturasinica.org/exist/apps/tcadrt/place/000001
and are now getting a 500 Tomcat error. Do you know how to fix this?

<img width="1024" alt="Screen Shot 2020-09-23 at 10 43 17 AM" src="https://user-images.githubusercontent.com/25234059/94036696-35507180-fd8a-11ea-81b0-612155ce0d82.png">

**Comment by wsalesky** [comment]
Sorry! That was my fault. It should be fixed now.

**Comment by millertg** [comment]
Whew! We were wondering what we could possibly have done 😊.
Thanks-
T

**Comment by millertg** [comment]
When I look for the TEI, I get the same error:
HTTP Status 500 - An error occurred while processing request to /exist/apps/tcadrt/place/000002.tei: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: concat($atomizable-values as xs:anyAtomicType?, ...) xs:string?. Expected cardinality: zero or one, got 5. [at line 49, column 33, source: /db/apps/tcadrt/controller.xql]

**Comment by wsalesky** [comment]
Fixed.
