### ISSUE TITLE
Bibliography search page broken

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#150]
@wsalesky the spaces for the refined search categories don't search the data. I get 0 results when searching my name, for example. Yet we have three of my publications in our bibliography, retrieved by searching in the top bar search window. Can we fix this so that we can make sure we don't add duplicate bibliographic records?

![Screen Shot 2020-11-04 at 1 42 46 PM](https://user-images.githubusercontent.com/25234059/98160356-b3cd2280-1ea3-11eb-9088-2902de7d08fb.png)

**Comment by wsalesky** [comment]
@millertg The search has been fixed. Please let me know if it is not working as expected. I will look into the bibl import function and see what is going wrong.

**Comment by millertg** [comment]
Thank you for looking into this. It is working better, but I don't get any results when I search for publication place or publisher name. I tried both Chinese and English and neither returned a search result.

**Comment by wsalesky** [comment]
@millertg how does the search look now?

**Comment by millertg** [comment]
@wsalesky Much better!
