### ISSUE TITLE
Site 000285 returned error

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#159]
@wsalesky 
the pages for Lingyinsi are showing errors. Can you tell what the cause might be?
https://architecturasinica.org/place/000285
https://architecturasinica.org/place/000285a
https://architecturasinica.org/place/000285b
![Screen Shot 2020-12-08 at 10 21 49 AM](https://user-images.githubusercontent.com/25234059/101510178-3895db00-393f-11eb-82a1-2a90ed2505e6.png)

**Comment by wsalesky** [comment]
fixed.

**Comment by millertg** [comment]
Thank you!
