### ISSUE TITLE
Terminology search and display unpredictable

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#160]
@wsalesky 
Are you working on the terminology section https://architecturasinica.org/terminology.html? The page has been behaving strangely. 

If you just click on the link in the top bar you see the first page of terms, but the nav bar on the left doesn't include much any more: 
![Screen Shot 2020-12-09 at 10 03 06 AM](https://user-images.githubusercontent.com/25234059/101658367-90e5df00-3a0a-11eb-9c77-cd1c43e8cd46.png)

Then, if you click the NEXT or ALL at the bottom of the page the order of the terms changes so that they are no longer listed alphabetically: 
![Screen Shot 2020-12-09 at 10 20 19 AM](https://user-images.githubusercontent.com/25234059/101658574-c4286e00-3a0a-11eb-9faf-c3c6de32d43d.png)

Can you figure out what is wrong?

**Comment by wsalesky** [comment]
@millertg I will take a look.

**Comment by wsalesky** [comment]
@millertg Please take a look and let me know if this is fixed.

**Comment by millertg** [comment]
This is better, but strangely, when you go to the next page, it skips some of the terms. see the following screenshots:
Page 1 ends at 20
![Screen Shot 2020-12-10 at 5 24 20 PM](https://user-images.githubusercontent.com/25234059/101865180-35ffd500-3b3b-11eb-8691-358bb31b7df7.png)

But look at Page 2--it starts at 25:
![Screen Shot 2020-12-10 at 5 24 33 PM](https://user-images.githubusercontent.com/25234059/101865234-59c31b00-3b3b-11eb-9fa4-2692f9155f6a.png)

Can you figure out why it would do that?

**Comment by wsalesky** [comment]
Opps! Should be fixed.

**Comment by millertg** [comment]
@wsalesky Thank you!
