### ISSUE TITLE
terrain map display not loading

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#161]
@wsalesky Since 12/15 the terrain display on the map is not loading
![Screen Shot 2020-12-16 at 10 48 24 AM](https://user-images.githubusercontent.com/25234059/102388963-1c75e780-3f98-11eb-9a8f-345338e42db1.png)

**Comment by wsalesky** [comment]
@millertg So sorry! There have been some odd things happening with the MapBox tiles. I keep having to switch base tiles. I will do some more research on best tiles to use, but for now at least they are rendering.
