### ISSUE TITLE
"place type" in Dynamic Site Archive

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#163]
@wsalesky @shubenda 
Winona--do you know how to remove and/or modify the "place type" that appears at the top of the Dynamic Site Archive pages? I don't remember seeing it before, but it might be useful, if we could use this to add site and building types linked to the thesaurus (e.g. monastery, pagoda) at the top of the page. But I don't know where it appears in the TEI. 

See, for example: 
https://architecturasinica.org/place/000191
![Screen Shot 2020-12-31 at 12 27 30 PM](https://user-images.githubusercontent.com/25234059/103421816-f0e02900-4b63-11eb-8c2a-560e5daadbbe.png)

**Comment by wsalesky** [comment]
@millertg You can remove this line: 
https://github.com/VandyVRC/srophe-eXist-app/blob/master/geo/record.html#L6

(Or I can if you do not want to edit the HTML).

**Comment by millertg** [comment]
Done--thank you!
