### ISSUE TITLE
displaying "content-author" 

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#172]
@wsalesky 
Can the "content-author" be listed as the Author under the AS "How to cite this entry"? Previously only the "creator" was displayed as an author of a file in AS. We added "content-author" as a new role in our responsibility statement, and the display no longer shows the "content-author" as the author of the entry for citation purposes.  See attached.

![Screen Shot 2021-03-07 at 1 14 55 PM](https://user-images.githubusercontent.com/25234059/110251973-d0a85e00-7f48-11eb-8379-e6304c1e522e.png)
![Screen Shot 2021-03-07 at 1 15 11 PM](https://user-images.githubusercontent.com/25234059/110251981-ddc54d00-7f48-11eb-8872-a51ae3bbe5a4.png)

**Comment by wsalesky** [comment]
Fixed.
