### ISSUE TITLE
create delete function on AS bibliography

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#177]
@wsalesky 
I can delete record in the AS library in Zotero, but when I update the AS library, the bibliographic record won't delete. This leads to serious confusion when we try to add a source to a new record.

For example, I deleted the extra record for an article by Susan Erickson earlier today, but it is still available for selection as a source in the forms. See attached. 
![Screen Shot 2021-03-15 at 7 24 37 PM](https://user-images.githubusercontent.com/25234059/111238389-0098d680-85c5-11eb-9ce9-e60c29166b50.png)

**Comment by wsalesky** [comment]
Okay, I will take a look.
