### ISSUE TITLE
bibliography search needs to include Extra field in Zotero for pinyinLC, pinyinCP, zh-Hans, and zh-Hant

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#199]
@wsalesky @shubenda 
We are adding additional scripts (pinyin) in the Extra field of Zotero. Can you make it so that our site will search for data in those fields? Also, do we need to add the Traditional characters to simplified entries (and vice-versa) for the search to be able to find them?

They are: 
Book pinyinLC:
Book pinyinCP:
Title pinyinLC: 
Title pinyinCP:
Journal pinyinLC: 
Journal pinyinCP: 
Author pinyin surname1: 
Author pinyin forename1: 
Author pinyin surname2: 
Author pinyin forename2:

**Comment by wsalesky** [comment]
@millertg 
What do each of those above fields map to in the TEI? 
Also, can I get some sample records that are using the fields in Zotero, I will need to run a few test runs to get everything in the right spot. 
Thanks!

**Comment by millertg** [comment]
@wsalesky @shubenda 
Here are a couple that might work. Thanks!
https://architecturasinica.org/keyword/k000103
https://architecturasinica.org/keyword/k000004

**Comment by wsalesky** [comment]
@millertg 
Which bibliography records? (You can even send me the link to the Zotero record if you want).

**Comment by millertg** [comment]
Can you write it so that it will apply to any record with Chinese authors and titles? Or non-Roman script authors and titles?

**Comment by wsalesky** [comment]
@millertg Yes. I just need some examples to make sure the code is working correctly before I move it to the server.

**Comment by millertg** [comment]
@wsalesky Ok. Here are three links to records in Zotero--2 through AS, and one directly to Zotero. Is this what you need?
https://www.zotero.org/groups/2267085/architecturasinica/items/CT4CSDB8
https://www.zotero.org/groups/2267085/architecturasinica/items/XRBQVWIX
https://www.zotero.org/groups/2267085/items/ZIPDD3MI
 https://www.zotero.org/groups/2267085/items/WHTF8Y2G

**Comment by wsalesky** [comment]
@millertg I think I have a working solution, I will update the bibliography records tonight and you can test it tomorrow and see if it is accomplishing what you want.

**Comment by wsalesky** [comment]
@millertg The bibliography records have been updated. Please let me know if this resolves the issue.

**Comment by millertg** [comment]
@wsalesky 
Did you already code to search for "Book" and "Journal" titles?

In my ignorance of Zotero, I didn't realize that you were pulling the Publication type from them. So, instead of distinguishing book or journal titles in the Extra field (which we haven't started doing yet), maybe we should code for publication instead-since that automatically appears as a category once one selects Journal or Chapter as an item type? That is, instead of-
Book pinyinLC:
Book pinyinCP:
Journal pinyinLC:
Journal pinyinCP:

We just use-
Pub pinyinLC: 
Pub pinyinCP:
in the case of the entry being part of a larger work? Does that make sense?

**Comment by millertg** [comment]
@wsalesky 
I added the Pub pinyinLC and CP to this record:
https://architecturasinica.org/bibl/X76NQT7M
If you want to test it. Below is what it looks like now.
Thanks!!!
![Screen Shot 2021-06-29 at 11 16 50 PM](https://user-images.githubusercontent.com/25234059/123901322-5739de80-d930-11eb-838d-6861aa4b8fb4.png)

**Comment by wsalesky** [comment]
@millertg Please check now. I think I got it right this time!

**Comment by millertg** [comment]
It is much closer!!
![Screen Shot 2021-06-30 at 9 37 24 AM](https://user-images.githubusercontent.com/25234059/123980722-61d39280-d987-11eb-9de3-7523fd85ce12.png)

**Comment by wsalesky** [comment]
@millertg This should do it.

**Comment by millertg** [comment]
Almost--I was counting on the publication hierarchy! Sorry...

![Screen Shot 2021-06-30 at 10 56 21 AM](https://user-images.githubusercontent.com/25234059/123994246-ccd69680-d992-11eb-84ab-df3a2bd2d1c7.png)

**Comment by wsalesky** [comment]
@millertg I updated the TEI generation and re ran the data. It looks like there may be an error in the Zotero data that if fixed should get the display you like: 
https://www.zotero.org/groups/2267085/architecturasinica/items/ZXZBG7W5

There is no 'Pub pinyinLC', the XQuery is looking for exact matches, and will not find anything that does not match the pattern above. So try correcting the record, do an zotero2bibl update and see if that fixes the HTML display. 
Let me know!

**Comment by millertg** [comment]
@wsalesky 
I added some in, and it works! Yay! 
Quick question--would it be hard to add:
Author surname zh-Hans: 
Author forename zh-Hans: 
Author pinyin surname: 
Author pinyin forename: 

Right now the code only finds authors if there is more than one. In that case we designate by adding numbers, to match with the Chinese.
Author pinyin surname1: 
Author pinyin forename1: 
Author pinyin surname2: 
Author pinyin forename2: 

If that is clumsy, we can add the number "1" to our preexisting records, we just need to change the style sheet.

**Comment by wsalesky** [comment]
That would be fine, just make sure I know what all the fields are named. I will be on vacation this weekend, but can make the changes next week.

**Comment by millertg** [comment]
Ok, terrific. We have other things mentioned, but have done so to enhance the search. Can you also make it so that the  Bibliography search fields point also to the Extra field?
Have a nice holiday weekend!

**Comment by wsalesky** [comment]
@millertg I updated the code, but I did not rerun the Zotero -> bibl transformation, would you like me to, or are these additions you still have to make to the Zotero records.

**Comment by millertg** [comment]
@wsalesky Quick question--do you happen to know if there is a code to search for alternate versions of a Chinese character? i.e. either simplified or traditional regardless of what is typed in?

**Comment by millertg** [comment]
@wsalesky Here are the fields I am currently hoping to include, depending on the case. If there is a way to set up a search so that we don't need to include alternate forms of characters, then we wouldn't need to have the zh-Hant entries below. Also, it would be rare to have 3 authors, but it might happen. In which case we would add a numeral 3 in the appropriate space below. Can you code it so that the computer looks for "any number"? Something like: Author pinyin surname#:  ?
Title zh-Hant:
Title pinyinLC: 
Title pinyinCP:
Pub pinyinLC:
Pub pinyinCP:
Author surname zh-Hant:
Author forename zh-Hant: 
Author surname zh-Hant1:
Author forename zh-Hant1: 
Author surname zh-Hant2:
Author forename zh-Hant2:
Author pinyin surname:
Author pinyin forename:
Author pinyin surname1: 
Author pinyin forename1: 
Author pinyin surname2: 
Author pinyin forename2:

**Comment by wsalesky** [comment]
@millertg Okay, give this a try.

**Comment by millertg** [comment]
tested this one: https://architecturasinica.org/bibl/FAJ6HHYJ

It started with no number after author pinyin

![Screen Shot 2021-07-06 at 10 22 52 PM](https://user-images.githubusercontent.com/25234059/124697002-b5743d80-deab-11eb-9bf1-53976c07a0ae.png)

But no author would display:

![Screen Shot 2021-07-06 at 10 23 29 PM](https://user-images.githubusercontent.com/25234059/124697037-c15fff80-deab-11eb-9fd4-d9ee7958f885.png)

I changed it to add a number: 

![Screen Shot 2021-07-06 at 10 42 19 PM](https://user-images.githubusercontent.com/25234059/124697086-d5a3fc80-deab-11eb-87f9-7b7af36ccb89.png)

author's name is displayed in pinyin:

![Screen Shot 2021-07-06 at 10 46 15 PM](https://user-images.githubusercontent.com/25234059/124697410-4f3bea80-deac-11eb-805e-73291536b078.png)

But only the first author should be listed (for the article). We have no space to enter the name of the author of a publication.

**Comment by wsalesky** [comment]
@millertg How about now?

**Comment by millertg** [comment]
@wsalesky Still no pinyin for author's name

![Screen Shot 2021-07-07 at 10 38 52 AM](https://user-images.githubusercontent.com/25234059/124790604-e9357e80-df10-11eb-9a58-5d9630ddb82c.png)

**Comment by wsalesky** [comment]
@millertg Hopefully this resolves the issue. I misunderstood how you wanted the display.

**Comment by millertg** [comment]
It works! 
![Screen Shot 2021-07-07 at 9 32 03 PM](https://user-images.githubusercontent.com/25234059/124853023-cf288a00-df6a-11eb-8c71-140c9d3309e9.png)
![Screen Shot 2021-07-07 at 9 27 58 PM](https://user-images.githubusercontent.com/25234059/124853028-d2237a80-df6a-11eb-8448-02589ac61bff.png)

**Comment by millertg** [comment]
@wsalesky But, I am sorry to say, the author search still doesn't find things. 

![Screen Shot 2021-07-07 at 9 41 21 PM](https://user-images.githubusercontent.com/25234059/124854898-b9689400-df6d-11eb-893d-a7737a07fd7c.png)

![Screen Shot 2021-07-07 at 9 41 47 PM](https://user-images.githubusercontent.com/25234059/124853987-5aeee600-df6c-11eb-8f2c-0fcf214e978d.png)

**Comment by wsalesky** [comment]
@millertg this is what I get when I search: 
<img width="1626" alt="Screen Shot 2021-07-08 at 8 47 51 AM" src="https://user-images.githubusercontent.com/1168206/124924285-4e4cab00-dfc9-11eb-97a1-3845834fa889.png">

If this is what you are expecting, then I think you just need to do a hard refresh of your browser. If not I will need to rerun the index.

**Comment by millertg** [comment]
@wsalesky I shouldn't be seeing the authors' names as second names in pinyin as they are no longer appear that way in Zotero. At present we are only putting the pinyin names in the extra field:
https://www.zotero.org/groups/2267085/architecturasinica/items/PDU6MSVF
 Can you rerun the index?
Thanks!!

**Comment by wsalesky** [comment]
@millertg The zotero record has to be mapped to TEI, there is no extra field in the TEI, I have been mapping them to author fields with a type="alt" attribute. It sounds like this is not how you want them mapped? Is the problem with the mapping or the display in the search? Do you want to arrange a quick call tomorrow to discuss?

**Comment by millertg** [comment]
@wsalesky @shubenda 
a call sounds like a good idea. I am adding Yuh-Fen into this. Would sometime around 9 CST/10 EST work for both of you?

**Comment by wsalesky** [comment]
That sounds great.
-Winona

**Comment by millertg** [comment]
@wsalesky 
Noticed 2 things when testing last (and you are going to kill me...): 
1. I lost a citation--have you updated the bibliography?

2. We really need to show editors, when they are there. Seems like Editor doesn't appear when there is not also a forename.
![Screen Shot 2021-07-10 at 10 38 43 AM](https://user-images.githubusercontent.com/25234059/125168456-4dec1580-e16b-11eb-85b4-113574cb4684.png)

Also, I didn't mention this before, because I forgot. Some works only have "editors," and not authors, such as dictionaries. When this happens, we also add the editor's name in the Extra field: 
Editor pinyin surname: (with and without numbers)
Editor pinyin forename:
Editor zh-Hans:
Editor zh-Hant:

**Comment by millertg** [comment]
@wsalesky 
Here is the TEI with Zotero code for the missing citation:
<bibl xml:id="biblk000103-2">
<ptr target="https://architecturasinica.org/bibl/G3VB5QMD"/>
<citedRange unit="pp">349</citedRange>
</bibl>
![Screen Shot 2021-07-10 at 10 42 32 AM](https://user-images.githubusercontent.com/25234059/125168580-d66ab600-e16b-11eb-80f6-4ceed541b2b5.png)

**Comment by wsalesky** [comment]
@millertg how does it look now?

**Comment by millertg** [comment]
@wsalesky 
Much better! I see all the entries now! Yay!!
For the Bibliography entry, there are a couple of tiny things: 
![Screen Shot 2021-07-10 at 8 38 11 PM](https://user-images.githubusercontent.com/25234059/125180408-5f5f0d00-e1bf-11eb-8a0e-7b17397a4457.png)

Do you ever long for a Zotero voodoo doll?
