### ISSUE TITLE
doubling in architectural terminology display

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#202]
@wsalesky @shubenda 
Can we make it so that terms marked as "alternate" are not displayed in the terminology list? Currently, terminology display pulls, I think, from zh-pinyin. when we have alternates, it will combine them. It has done this with two: 
https://architecturasinica.org/keyword/k000024
and
https://architecturasinica.org/keyword/k000023
<img width="509" alt="Screen Shot 2021-05-31 at 3 30 40 PM" src="https://user-images.githubusercontent.com/25234059/120240556-7c9ad600-c226-11eb-82a3-9482e4029f5f.png">
![Screen Shot 2021-05-31 at 3 31 09 PM](https://user-images.githubusercontent.com/25234059/120240612-a05e1c00-c226-11eb-8c42-9a338b902117.png)

**Comment by wsalesky** [comment]
@millertg what is that first screen shot from? A search? If you could past in a link that would be great. thanks

**Comment by millertg** [comment]
@wsalesky It was from a search: 
https://architecturasinica.org/terminology.html?q=touxinzao&term=

**Comment by wsalesky** [comment]
@millertg I think this issue has been resolved. If not please re-open and let me know what I missed. Thanks!

**Comment by millertg** [comment]
The alternates have been removed from the index (which is great), but we can no longer see them in the display.
![Screen Shot 2021-06-02 at 1 19 12 PM](https://user-images.githubusercontent.com/25234059/120535346-7e8ca280-c3a8-11eb-9aed-13435da14d03.png)

**Comment by wsalesky** [comment]
@millertg Sorry! I misread the issue and thought that was what you wanted. i will put them back in the display.

**Comment by millertg** [comment]
That’s ok! They were just showing together with the other version, so before as search for jixinzao resulte in:
jixinzaojixin

Rather than
jixinzao
jixin

Do we need to have a separate record for an alternate rendering of a “concept”/ term? We had done that, and wanted to simplify since the two different terms are the same concept. But the Getty has two records and cross-references them. Perhaps that is the best solution for us as well?

Still, we will need to be able to have the code look for zh-pinyin for the search result display, and not zh-pinyin type=alternate.

Does that make any sense?

Thanks-
Tracy

--
Tracy Miller
Associate Professor
Department of History of Art and Architecture
Department of Asian Studies
Vanderbilt University

From: Winona Salesky ***@***.***>
Date: Wednesday, June 2, 2021 at 1:45 PM
To: VandyVRC/srophe-eXist-app ***@***.***>
Cc: Miller, Tracy G <tracy.g.miller@Vanderbilt.Edu>, Mention ***@***.***>
Subject: Re: [VandyVRC/srophe-eXist-app] doubling in architectural terminology display (#202)

@millertg<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmillertg&data=04%7C01%7Ctracy.g.miller%40vanderbilt.edu%7C0721e874a56d43ebd83208d925f692be%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637582563218287761%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JzCctTFoe9Ud2v0rAO7ZTXjNnFU4wgaNXxgAthe7%2FTI%3D&reserved=0> Sorry! I misread the issue and thought that was what you wanted. i will put them back in the display.
