### ISSUE TITLE
bibliography search not functioning

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#206]
@wsalesky something is broken, my searches yield 0 results
![Screen Shot 2021-06-11 at 1 22 01 PM](https://user-images.githubusercontent.com/25234059/121732632-1892d000-cab8-11eb-9274-1c47f82d0789.png)
![Screen Shot 2021-06-11 at 1 18 12 PM](https://user-images.githubusercontent.com/25234059/121732638-1a5c9380-cab8-11eb-8c30-214697fa0187.png)

**Comment by wsalesky** [comment]
fixed.
