### ISSUE TITLE
remove source information from popups

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#21]
@wsalesky source for date comes up as building name, do you know why?
![screen shot of shanmen search](https://user-images.githubusercontent.com/25234059/34051503-7ee60ffa-e184-11e7-918b-c163ceecf90e.png)
can we pull this source from popups?

**Comment by wsalesky** [comment]
Looks like a bug.

**Comment by wsalesky** [comment]
Related problems here: http://tcadrt-exist-2.jelastic.servint.net/exist/apps/tcadrt/search.html?q=mountain+gate

and here: http://tcadrt-exist-2.jelastic.servint.net/exist/apps/tcadrt/place/000129
