### ISSUE TITLE
switching to simplified author-date reference list

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#211]
@wsalesky @shubenda 
For our reference, we are switching to Chicago, Author-Date style, and are using a simplified version. 
Footnote: Author surname. year. title of book or article, cited-range.

**Comment by millertg** [comment]
@wsalesky @shubenda 
Chinese script titles should be in double brackets: 《》

**Comment by wsalesky** [comment]
@millertg This is fixed.

**Comment by millertg** [comment]
@wsalesky 
Yay!! I love the 《》!!
