### ISSUE TITLE
data spreadsheet download update

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#213]
@wsalesky Previous links for spreadsheet downloads are no longer working. 
![Screen Shot 2021-08-23 at 8 32 52 AM](https://user-images.githubusercontent.com/25234059/130456241-a61c6de1-554d-4421-ba18-fc301e3cc949.png)

Can these be easily repaired? We need them for submissions to the Getty at the end of the semester. Thank you!

**Comment by wsalesky** [comment]
@millertg Yes, it is an easy fix... will get to it today or tomorrow.

**Comment by wsalesky** [comment]
Should be fixed. Please test and close if yes.

**Comment by millertg** [comment]
@wsalesky it returns data, but not in the spreadsheet download format it used to.
![Screen Shot 2021-08-23 at 8 59 01 AM](https://user-images.githubusercontent.com/25234059/130460478-42440980-bbcc-480e-880d-e95df6e64806.png)

**Comment by wsalesky** [comment]
@millertg Should be fixed now. Sorry about that.

**Comment by millertg** [comment]
@wsalesky Thank you 🙏 🥳
