### ISSUE TITLE
Dev server still not completely updating

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#214]
@wsalesky @CliffordAnderson @shubenda 
I discovered a weird shadow in the dev server. We reused a number for a new site. But it refuses to update on the dev server. I this should either be a corrupt file or, perhaps,  web hooks? 

https://architecturasinica.org/place/000191/tei
This record used to be the Jin Shrines offering hall; changed to Longhua Monastery. The TEI record is updated in the dev repository, but not on the dev website. See screenshot. 

![Screen Shot 2021-08-25 at 8 39 13 AM](https://user-images.githubusercontent.com/25234059/130805533-5cdae92b-b17a-47f7-8ccf-f88b3ab22d41.png)

Interestingly, this is updating fine on the prod server. 

My homemade fix for a possible corrupt file would be: 1. save a copy of https://architecturasinica.org/place/000191/tei from theprod branch to my desktop, 2. delete the file from dev, 3. insert the prod file copy from my desktop into the dev server folder. 

Should I try that, or, do you think this is a web hook issue?

**Comment by wsalesky** [comment]
@millertg I see it on the dev server: https://dev.architecturasinica.org/place/000191a
