### ISSUE TITLE
trouble with srophe crashing?

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#215]
@wsalesky we have been working well on the dev site of tcadrt, but the production site has been showing a 502 Error. It reboots, only to crash again.

**Comment by millertg** [comment]
@wsalesky can you tell me which image of the app we should pull from Docker if we (Cliff, Yuh-Fen, and I) want to be able to service it locally?

**Comment by wsalesky** [comment]
@millertg syriaca.org has been crashing a lot over the past few days as well, we are working on fixing it, and that should help with tcadrt as well. You can use the latest version from DockerHub: https://hub.docker.com/repository/docker/srophe/tcadrt

However you will need to re-deploy the latest version into the app to run it locally. (fetch the latest from github, run 'ant' and drop the .xar file into your local version of eXist-db. Cliff should be able to help with that).

**Comment by millertg** [comment]
@wsalesky @CliffordAnderson @shubenda Ok, we will give it a shot and see if we run into any errors. Thanks so much!
