### ISSUE TITLE
spreadsheet download categories

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#218]
@wsalesky Help! Can you tell us how to tag our note fields so that they appear in the columns you already have set up for us? We want to tag our Getty scope note-en and hant, but can't figure out how to do so (see screenshot). We are just using note type=brief for the moment. What attribute are we missing?  If we could know by tomorrow then I could have the kids add the tag before a meeting on Thursday. Thank you!
![Screen Shot 2021-11-02 at 2 48 48 PM](https://user-images.githubusercontent.com/25234059/139942166-ac7c629e-9967-4833-9a48-7f36e4803316.png)

**Comment by wsalesky** [comment]
@millertg This is what the code is looking for: 
`tei:note[@type="getty:scopeNote" or @type="Scope Note"]/tei:p[@xml:lang = 'en'`

and  

`/tei:note[@type="getty:scopeNote" or @type="Scope Note"]/tei:p[@xml:lang = 'zh-Hant']`

Does that  help?

**Comment by millertg** [comment]
Yes! I will try it tonight. Thank you!

**Comment by wsalesky** [comment]
@millertg Just checking in, is this resolved?

**Comment by millertg** [comment]
@wsalesky yes, in a manner of speaking. I was able to use that tag and see the data in the tsv download. However, what I would like to do is to have a tag for a text paragraph that will pull one paragraph (actually 2, one in English one in Chinese) of text from within a "note" into a separate column, without displaying anything on the webpage. Do you happen to have an instant solution for that :-)?

**Comment by wsalesky** [comment]
@millertg  I'm not sure I completely understand. Can you give me an example. The XML, and then how you want it to appear in the download?

**Comment by shubenda** [comment]
@wsalesky I just tried with tei:note[@type="Scope Note"]/tei:p[@xml:lang = 'en'] and tei:note[@type="Scope Note"]/tei:p[@xml:lang = 'zh-Hant'], see example: https://dev.architecturasinica.org/keyword/k000154
I duplicate the first sentences for both Chinese and English. but the duplicate contents don't show up either under Getty note or brief note. 
now sure what went wrong. can you help?

**Comment by millertg** [comment]
@wsalesky @shubenda 
Let me explain what we are trying to do. more in a second (building screenshots)

**Comment by millertg** [comment]
@wsalesky @shubenda experimenting on this record: https://dev.architecturasinica.org/keyword/k000154
trying to have Getty subsection of our Note (full) display in separate column


![Screen Shot 2021-11-03 at 2 13 54 PM](https://user-images.githubusercontent.com/25234059/140177844-ac5b5fa7-3c64-444c-b4d0-183253180dda.png)
![Screen Shot 2021-11-03 at 1 50 20 PM](https://user-images.githubusercontent.com/25234059/140177643-74d244f7-7caa-4b20-b1b0-17d93407936d.png)

![Screen Shot 2021-11-03 at 2 11 46 PM](https://user-images.githubusercontent.com/25234059/140177452-8aa802b4-e391-4337-a323-f6133ce33e65.png)

**Comment by wsalesky** [comment]
@millertg Try now: https://dev.architecturasinica.org/modules/data.xql?format=tsv&collection=keywords

**Comment by millertg** [comment]
@wsalesky @shubenda 
By george, I think you have done it. It works for zaojing--Yay!! Thank you! Yuh-Fen, do you want to give it a try with a different term?
![Screen Shot 2021-11-03 at 6 22 36 PM](https://user-images.githubusercontent.com/25234059/140232435-1b2ec2dd-ecdb-4c14-9f9f-516c921ef692.png)

![Screen Shot 2021-11-03 at 6 22 36 PM](https://user-images.githubusercontent.com/25234059/140232411-e575c5d2-1168-4734-9ddf-4e2cfa4059f7.png)

**Comment by shubenda** [comment]
@wsalesky@millertg 
yes, it works. Thank you, Winona! 
I just updated the: https://dev.architecturasinica.org/keyword/k000179
Is this the link we should use to download the keywords in the future? https://dev.architecturasinica.org/modules/data.xql?format=tsv&collection=keywords
