### ISSUE TITLE
merging

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#220]
@wsalesky @CliffordAnderson @shubenda I just merged dev to production, and it didn't change anything on the website. Winona--can you see any immediate mistakes?

**Comment by wsalesky** [comment]
fixed

**Comment by millertg** [comment]
I made a couple of minor modifications in dev for a meeting tonight, and merged it with production, but the production server did not update.
compare: 
https://architecturasinica.org/keyword/k000194
https://dev.architecturasinica.org/keyword/k000194

**Comment by wsalesky** [comment]
@millertg There was a permissions problem on the webhooks, should be working now. I pushed those changes again, everything looks okay except: tcadrt-data/data/places/buildings/tei/000048ma.xml

This is producing an error, looks like the XML is not correct: "The XML parser reported a problem: fatal error at (71,45) : Open quote is expected for attribute "from" associated with an  element type  "state". XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: The XML parser reported a problem: fatal error at (71,45) : Open quote is expected for attribute "from" associated with an  element type  "state"."

**Comment by millertg** [comment]
@wsalesky Thank you!
