### ISSUE TITLE
exerr:ERROR Exception while transforming node

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#227]
@wsalesky @shubenda 
So, I just updated the production server, and some of the files are fine. But this entry on “ta” (pagoda) generated an error in the production server (https://architecturasinica.org/keyword/k000060), even though it displays fine in dev. Can you tell what is going on?(https://dev.architecturasinica.org/keyword/k000060). 
![Screen Shot 2022-07-22 at 2 22 32 PM](https://user-images.githubusercontent.com/25234059/180513421-11d90c3d-688f-4f59-a3c7-78109087ccce.png)

**Comment by wsalesky** [comment]
The problem is right here: 
https://github.com/VandyVRC/tcadrt/blob/master/data/keywords/tei/k000060.xml#L105

This bibl does not have an xml:id, it has a source attribute instead. So change line 105 from: 

`<bibl source="biblk000060-2">`

to: 

`<bibl xml:id="biblk000060-2">`

That should fix the error.

**Comment by millertg** [comment]
It worked! Thank you!!!
I have fixed that type of error before—hopefully I will recognize it next time.

Thanks, again!
Tracy

From: Winona Salesky ***@***.***>
Date: Friday, July 22, 2022 at 9:17 PM
To: VandyVRC/srophe-eXist-app ***@***.***>
Cc: Miller, Tracy G ***@***.***>, Assign ***@***.***>
Subject: Re: [VandyVRC/srophe-eXist-app] exerr:ERROR Exception while transforming node (Issue #227)

The problem is right here:
https://github.com/VandyVRC/tcadrt/blob/master/data/keywords/tei/k000060.xml#L105<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVandyVRC%2Ftcadrt%2Fblob%2Fmaster%2Fdata%2Fkeywords%2Ftei%2Fk000060.xml%23L105&data=05%7C01%7Ctracy.g.miller%40vanderbilt.edu%7Ce66c5b4e6fe7462fc45508da6c5172a8%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637941394320965898%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LFBGstLVwNXPN3%2BEcSrncEVCH1AfpViNW9VxFnM6vxw%3D&reserved=0>

This bibl does not have an xml:id, it has a source attribute instead. So change line 105 from:

<bibl source="biblk000060-2">

to:

<bibl xml:id="biblk000060-2">

That should fix the error.
