### ISSUE TITLE
dev server English Zotero entries not displaying 

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#228]
@wsalesky the dev server is not showing the English language Zotero information.
I updated a page and noticed that the works cited entries on dev are not loading properly. I ran an update on both the dev and prod servers, but it didn't help. I tried to "initiate" the bibliography, but received an error after updating through 500 entries. 
The prod server works cited looks fine.

I have attached a screenshot of both dev and prod servers
![Screen Shot 2022-08-07 at 9 21 24 PM](https://user-images.githubusercontent.com/25234059/183328216-a5f3291d-cb0e-47db-8e4b-80e1e4ab98ab.png)
![Screen Shot 2022-08-07 at 9 20 46 PM](https://user-images.githubusercontent.com/25234059/183328229-3a130c8e-f80f-410a-b52a-149b059b20eb.png)
.

**Comment by wsalesky** [comment]
@millertg how does it look now? I reran the zoter2bibl script. Sometime when you run it you get a service denied error, just give it a few minutes and try again (from where you got the error, don't start all over), Zotero does some rate limiting.

**Comment by millertg** [comment]
@wsalesky Looks good now--thank you! Nice to know that about Zotero. I am usually pretty patient, but it was the service denied error that threw me.

**Comment by wsalesky** [comment]
Yes, it can get confusing. I should probably do some additional documentation on the app so when you get that you know what to do!

**Comment by millertg** [comment]
*Additional* documentation? So, this is embarrassing…is the other zotero2bibl documentation somewhere on Github🙃?


From: Winona Salesky ***@***.***>
Date: Tuesday, August 9, 2022 at 10:33 AM
To: VandyVRC/srophe-eXist-app ***@***.***>
Cc: Miller, Tracy G ***@***.***>, State change ***@***.***>
Subject: Re: [VandyVRC/srophe-eXist-app] dev server English Zotero entries not displaying (Issue #228)

Yes, it can get confusing. I should probably do some additional documentation on the app so when you get that you know what to do!

**Comment by wsalesky** [comment]
Technically there is a very small amount of documentation (https://github.com/srophe/zotero2bibl). What I should do is add a message for when you get a service denied error that lets you know to retry your request in a few minutes.

**Comment by millertg** [comment]
@wsalesky that would be great!
