### ISSUE TITLE
site and building name should be combined

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#23]
@wsalesky search for mountain gate returns numerous mountain gates from which to choose. Can we combine site name and building name in search results? And in the titles on returns? So that, in the example below, you would see: Chongjiao Monastery Mountain Gate 崇教寺山門？
![site separated from building name](https://user-images.githubusercontent.com/25234059/34052043-58ab6522-e186-11e7-9376-c50be7a2facb.jpg)

**Comment by wsalesky** [comment]
Yes, do you want this to be the title of the record, or only when it is returned in a search? (My recommendation would be to put it in the title of the TEI.) Let me know which you prefer.

**Comment by millertg** [comment]
We might need to do both, but I am not sure. I should also see the name of the site on the return for any building type search I might do. So, the return for "shanmen" should include the name of the site in which each shanmen appears (see below). If that were the title of the record, would that be the result?
![screen shot 2017-12-15 at 12 10 45 pm](https://user-images.githubusercontent.com/25234059/34054541-1b18e45e-e191-11e7-86c8-6281602a9afa.png)

**Comment by wsalesky** [comment]
Yes, that would be the result.

**Comment by millertg** [comment]
Then putting into the TEI would be fine. There should probably be a comma after the site name.

**Comment by wsalesky** [comment]
Added. Let me know what you think. If you like it, you may close the issue, if you would like to make any adjustments let me know.

**Comment by millertg** [comment]
Looks great. Before we close, is it possible to NOT have the site name included when listing the buildings (which for the sake of further development, should read: building(s)/artifact(s)).
![site page modification](https://user-images.githubusercontent.com/25234059/34083569-a5da2654-e338-11e7-8627-2ff92c1bbc7a.jpg)

**Comment by wsalesky** [comment]
Okay, how does it look now?

**Comment by millertg** [comment]
looks good! I have other modifications but I think we can close this issue.

**Comment by wsalesky** [comment]
Great!
