### ISSUE TITLE
data still not fully updating

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#232]
@wsalesky Data is still not fully updating. I added an image last week to dipeng (https://github.com/VandyVRC/tcadrt/blob/master/data/keywords/tei/k000209.xml)
But it doesn't show on either dev or prod.

**Comment by wsalesky** [comment]
I have never seen this error before: 
<img width="861" alt="Screenshot 2023-04-24 at 7 22 19 PM" src="https://user-images.githubusercontent.com/1168206/234136325-4feb5891-73e1-41bd-9380-aa43d22e1aee.png">

It is hard to debug if I can not even access the error. I will take a look at what is on the server tomorrow. See if there could be something on that end.
