### ISSUE TITLE
View in Mirador link

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#254]
@wsalesky The "view in Mirador" link for the watchtower is returning an error.
<img width="1095" alt="Screenshot 2023-09-19 at 3 30 40 PM" src="https://github.com/VandyVRC/srophe-eXist-app/assets/25234059/fa4073be-d0df-49a2-ad52-f0313609742d">

**Comment by wsalesky** [comment]
@millertg Interesting. I will see what I can do.

**Comment by wsalesky** [comment]
Fixed

**Comment by wsalesky** [comment]
Fixed, by adding to the controller (in the data app):
```
else
    (: everything else is passed through :)
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <set-header name="Access-Control-Allow-Origin" value="*"/>
        <cache-control cache="yes"/>
    </dispatch>

```

**Comment by millertg** [comment]
@wsalesky Great! can we change the text to say "View annotations in Mirador"?

**Comment by wsalesky** [comment]
Done

**Comment by millertg** [comment]
🎊 Thank you!!
