### ISSUE TITLE
Update searchTips.html

### ISSUE THREAD

**Issue by wsalesky** [VandyVRC/srophe-eXist-app#29]
These are specific to Syriaca.org, terms can be swapped out, or the whole thing could be rewritten.

**Comment by wbsealy** [comment]
I've seen this file as well when looking at the app in action and can address this...

**Comment by wsalesky** [comment]
@wbsealy Great! Thanks.

**Comment by wsalesky** [comment]
@wbsealy I think we agreed to just suppress searchTips, at least for now.
