### ISSUE TITLE
Zotero update dev server

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#298]
@wsalesky AS Dev server Zotero "update" erased all the old items when loading the new entries/material. When I tried to "initiate" to reload the whole library, I received an "internal server error" at 800.

**Comment by millertg** [comment]
<img width="904" alt="Screenshot 2024-06-24 at 11 27 21 AM" src="https://github.com/VandyVRC/srophe-eXist-app/assets/25234059/03e60a5d-cf9d-4556-9a91-0d5d46287050">

**Comment by wsalesky** [comment]
I will take a lookOn Jun 24, 2024, at 12:31 PM, Tracy Miller ***@***.***> wrote:﻿
Reopened #298.

**Comment by wsalesky** [comment]
How does it look now?

**Comment by millertg** [comment]
Worked! I was even able to successfully update 1 record. Yay!
