### ISSUE TITLE
Zotero in dev

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#300]
@wsalesky dev site Zotero update script shows 0 updates, but the bibliography has not loaded:  
![image](https://github.com/VandyVRC/srophe-eXist-app/assets/25234059/2cdb09e9-115a-46ee-8fd2-cbe802396678)
When I try to "initiate" I receive an internal server error.

**Comment by wsalesky** [comment]
@millertg I will take a look. Did you merge the tcdart data into the development data?

**Comment by millertg** [comment]
Not yet
tm

Sent from my iPhone

On Jun 27, 2024, at 12:57 PM, Winona Salesky ***@***.***> wrote:

﻿

@millertg<https://github.com/millertg> I will take a look. Did you merge the tcdart data into the development data?

**Comment by millertg** [comment]
Feel free to do that if you like :-). I would be grateful
tm

Sent from my iPhone

On Jun 27, 2024, at 12:57 PM, Winona Salesky ***@***.***> wrote:

﻿

@millertg<https://github.com/millertg> I will take a look. Did you merge the tcdart data into the development data?

**Comment by wsalesky** [comment]
okay

**Comment by wsalesky** [comment]
I merged master into dev and updated the dev deployment. How does it look now?

**Comment by millertg** [comment]
looks great--thank you!!!
