### ISSUE TITLE
Amend Architectural features TEI

### ISSUE THREAD

**Issue by wsalesky** [VandyVRC/srophe-eXist-app#38]
Use English title for tei:title. Add image from flicker, supplied by Tracy.

**Comment by wsalesky** [comment]
English title added. Waiting for images from @millertg

**Comment by millertg** [comment]
Do you know how the images are pulled from Flickr? I found a url, but to match it with formatting in the images.csv I have to manually trim the link. Can they be auto-generated somehow?
