### ISSUE TITLE
Add a Featured image from flicker images to Site TEI and html

### ISSUE THREAD

**Issue by wsalesky** [VandyVRC/srophe-eXist-app#39]

**Comment by wsalesky** [comment]
@millertg You can add a column for this to the spreadsheet and let me know when the image id's are added I will then rerun the XSLT and load the new data.

**Comment by millertg** [comment]
This is the "BB code" for sharing the image:  
[url=https://flic.kr/p/8mUuJp][img]https://farm5.staticflickr.com/4073/4831069771_14fcd97cc0_z.jpg[/img][/url][url=https://flic.kr/p/8mUuJp]Baitaisi exterior view of complex[/url] by [url=https://www.flickr.com/photos/30365320@N04/]Tracy Miller[/url], on Flickr

I like this because I can choose the size, but it seems cumbersome. Still, should I paste the above into the spreadsheet? Thx.

**Comment by wsalesky** [comment]
No, just use the image url. You can chose the size to request from flickr based on that last letter before the .jpg, which we will change programmatically, depending on the context.

**Comment by millertg** [comment]
It will look like this, correct?
https://www.flickr.com/photos/30365320@N04/4831355562/in/photolist-8mVY3m-8mSP9P-8mVXFQ-8mVYbE-8mSNP4-8mVXg1-8mSMV2-8mSN5c-8mSNfp-8mSNrn-8mSN9K-8mVXmU-8mVUE5-8mVUty-8mVV5u-8mSKgr-8kPtzY-8kPtrJ-8mSMrp-8mSLvc

**Comment by wsalesky** [comment]
No, we want just 
https://farm5.staticflickr.com/4073/4831069771_14fcd97cc0_z.jpg

From the "BB Code" if it is too cumbersome to parse it out by hand you can paste the whole BB code snippet into the spreadsheet and I will parse it with XSLT.

**Comment by wsalesky** [comment]
Images have been added. They still need to be styled.

**Comment by millertg** [comment]
Thanks. Both Site and Building page should have the following general layout. I'll email William about this as well. 
![image](https://user-images.githubusercontent.com/25234059/36399484-b3e38476-1591-11e8-8946-adf76c89dea6.png)

**Comment by millertg** [comment]
@wbsealy Can you style the Site and Building pages to have a separate column for a selected image? This will need to be done for the Architectural Features page as well. Thanks!
![image](https://user-images.githubusercontent.com/25234059/36399696-b3a4d392-1592-11e8-9821-429bb5f4a3cd.png)

**Comment by wsalesky** [comment]
@millertg @wbsealy This may be done. Reopen if not.
