### ISSUE TITLE
@wsalesky pulling images from Flickr

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#61]
Images pulled from Flickr are not filtered by building/artifact. Can this be fixed in Flickr so that one only sees the images specific to that structure? Or should they go under "site" rather than "building"? The screenshot in this message shows the result of the 1000 Buddhas Hall of Chongqing Monastery.
![screen shot 2018-03-09 at 2 23 10 pm](https://user-images.githubusercontent.com/25234059/37229603-20366316-23aa-11e8-973e-98a4ec847ea2.png)

**Comment by wsalesky** [comment]
Can you share the link where these are showing up incorrectly? Currently these are mapped in this file: https://github.com/VandyVRC/tcadrt/blob/master/temple-images/images.csv

**Comment by millertg** [comment]
Sure: https://architecturasinica-dev.app.vanderbilt.edu/exist/apps/tcadrt/place/000150

**Comment by wsalesky** [comment]
Thanks, I will take a look.

**Comment by wsalesky** [comment]
@millertg  

These are incorrectly mapped in the temple-images csv. We don't have a way to automate the connection with flickr. At least not yet (still working out the flickr API). So they will have to be reassigned manually in the https://github.com/VandyVRC/tcadrt/blob/master/temple-images/images.csv

**Comment by millertg** [comment]
Ok, will do.
