### ISSUE TITLE
@wsalesky placing citation information

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#62]
Endymion Wilkinson's _Chinese History: A Manual_ pp. 11-12 is in the wrong place, It was only for the dates of the dynasties, not for building information. I am not sure where it should appear, but it seems misplaced on the Building or Site pages.
https://architecturasinica-dev.app.vanderbilt.edu/exist/apps/tcadrt/place/000097

**Comment by wsalesky** [comment]
@millertg We should probably discuss how to link sources in the TEI records. It may be useful to rope @davidamichelson into the discussion as he is far more knowledgeable about the TEI then I am.

**Comment by millertg** [comment]
Sounds like a good idea.
