### ISSUE TITLE
@wsalesky location of citation information

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#63]
Endymion Wilkinson's _Chinese History: A Manual_ pp. 11-12 is in the wrong place, It was only for the dates of the dynasties, not for building information. I am not sure where it should appear, but it seems misplaced on the Building or Site pages.
https://architecturasinica-dev.app.vanderbilt.edu/exist/apps/tcadrt/place/000097

**Comment by wsalesky** [comment]
closing as duplicate of https://github.com/VandyVRC/srophe-eXist-app/issues/62
