### ISSUE TITLE
@wsalesky "Site Information" and "Building Information" 

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#64]
The "Brief Description" on the Site page might be better named "Site Information"  https://architecturasinica-dev.app.vanderbilt.edu/exist/apps/tcadrt/place/000002
Can we put that in the box directly under the image of the site?

Also, can we have a similar box for "Building Information" on the building pages? The information for that should also come from the buildings.csv, but from column M: building_data.

**Comment by wsalesky** [comment]
@millertg do you want to include the Site Information in the building pages? The site information is in the building.csv (column B).

**Comment by millertg** [comment]
No, the site information should be for the site, the building information should be for the building. I realize this is a bit confusing. The site information should always have been in the site.csv.
