### ISSUE TITLE
@winona Edit Names on Site page

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#65]
The names of the site and location on the Site page seems redundant, partly, I think, because it is coming from my spreadsheets and the Getty. https://architecturasinica.org/place/000001

Can we edit them so that we have less repetition and more consistency? See possible additions, below. 

Names [we should have this order for the others, as well, ie. English, Pinyin, Traditional Chinese, Simplified Chinese]
Anchan Monastery (English)
Anchansi (Pinyin)
安禪寺 (Traditional Chinese)
安禅寺 (Simplified Chinese)

Type [change to: English, Pinyin, Traditional Chinese, Simplified Chinese]
si (Pinyin)
寺 (Traditional Chinese)
monastery (English)

Location
山西省太谷县 [add pinyin-which appears under Locality (English) below, but only the last three characters...]

China [add Traditional and Simplified Chinese?]

Province-name [this can be eliminated, as it appears below]:
山西 (Simplified Chinese)
山西 (Traditional Chinese)
Shanxi (Pinyin)

Province [change to Pinyin, Traditional Chinese, Simplified Chinese]:
山西省 (Simplified Chinese)
山西省 (Traditional Chinese)

County-city [change to Pinyin, Traditional Chinese, Simplified Chinese]:
太谷 (Simplified Chinese)
Taigu (Pinyin)
Political-subdivision:
县 (Simplified Chinese)
County (English)

Locality:
Taiguxian (English) [This should be "pinyin", as it would be Taigu County, or Great Valley County, in English] Maybe a Getty TGN designation, or not? http://www.getty.edu/vow/TGNFullDisplay?find=taigu&place=&nation=&prev_page=1&english=Y&subjectid=8677393

**Comment by wsalesky** [comment]
@millertg Is there a list that maps all the names for site types. I don't always know which part of the Chinese text is the site type in the spreadsheet. 

For most of them it looks like the last character but that is just me guessing.

 If you could make up a little spreadsheet with all the types and the English, Pinyin, Traditional Chinese, Simplified Chinese variants that would be useful.  

ex: monastery, si, 寺, Simplified Chinese varient. 

Thanks.

**Comment by millertg** [comment]
Here are the sites. I will do another for buildings. 
[site types.xlsx](https://github.com/VandyVRC/srophe-eXist-app/files/1803763/site.types.xlsx)

**Comment by wsalesky** [comment]
Wonderful, thanks.

**Comment by millertg** [comment]
I think these are all the building types I currently have. They defy simple description. Maybe we could build that into a Pictorial Dictionary/Glossary function.
[building types.xlsx](https://github.com/VandyVRC/srophe-eXist-app/files/1804101/building.types.xlsx)

**Comment by wsalesky** [comment]
Yes I think that would be useful. (Adding them to the Glossary). 

For building types, can you tell me how to tell the difference (in the building.xml) between: pagoda and stūpa? I don't see 'stūpa' in the building.csv, and the Chinese and Pinyin look the same. 

Thanks, 
-Winona

**Comment by millertg** [comment]
They are the same in Chinese, but religious historians often translate the word "ta 塔" as stupa, so I thought I would add a line. It could also be an alternative translation, or I guess a search for stupa could redirect to pagoda?

**Comment by wsalesky** [comment]
I think an alternative translation would probably work. Let me check the TEI

**Comment by wsalesky** [comment]
Okay. I have created individual records for these, and added 'supta' as an alternative translation to the pagoda file. These files will live in the 'keyword' directory, we can discuss how/if to search and display them.

**Comment by wsalesky** [comment]
@millertg We seem to be missing a building type 'Gate'? See 000076 or 000226. and site type 'Cloister' see: 000039.

Thanks.

**Comment by wsalesky** [comment]
@millertg I think I caught all of these. Reopen if I missed anything.
