### ISSUE TITLE
Content for pages linked on new home page. 

### ISSUE THREAD

**Issue by wsalesky** [VandyVRC/srophe-eXist-app#67]
@millertg We should provide pages for the links on the new homepage, even short descriptions of upcoming features would be fine.

Pages listed: 

1. 甲 Digital Research Tool - I am working on this
2. 乙 Geolocation - Do you want a map here? Or are you thinking of something else?
3. 丙 Image Archive - Should we pull in all Flickr images?
4. 丁 Epigraphy - Is this a 'in development' feature? Can we a have a page with a short description or should we suppress this line? 

Thanks!

**Comment by millertg** [comment]
乙 Geolocation - Do you want a map here? Or are you thinking of something else?--This might be a good place for the Browse all sites feature for now. I was hoping to figure out how to layer historic maps in this area. At which point it would be called Geolocation/Historic mapping.
丙 Image Archive - Should we pull in all Flickr images? At this point I am not sure how well that would work. Maybe we should change this to Pictorial Dictionary of Architectural Features?

**Comment by wsalesky** [comment]
@millertg Sounds good. Thanks.
