### ISSUE TITLE
@winona building dates

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#70]
I just noticed that there is no dynastic date column on the building spreadsheet. Should I add one now so that the building date appears when you click over to the building page?

**Comment by millertg** [comment]
and if so, does it matter where in the buildings.csv I add it?

**Comment by wsalesky** [comment]
Yes please put it in. And no it does not matter where. Just give it a
descriptive name.
Thanks,
-Winona

**Comment by wsalesky** [comment]
Actually I have dates in the building records. (I grabbed them from the matching site.) If they are dated differently then the sites, you should add a new column, otherwise you can leave as is.

**Comment by wsalesky** [comment]
@millertg I think this can be closed?
