### ISSUE TITLE
Remove redundant information on the buildings page

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#76]
2 things can be removed from this page https://architecturasinica-dev.app.vanderbilt.edu/exist/apps/tcadrt/place/000124: 
1. the last line under "Names"--this seems to be coming from column S "alternate_building_name_pinyin". I don't think we need to use this column at all anymore.
2. "Site Information" I think this only needs to appear on the site page. Maybe a link back to that page, instead?

**Comment by wsalesky** [comment]
Fixed
