### ISSUE TITLE
select site or building on geolocation page

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#86]
@winona Because the dates are different (or should be?) when searching from building.csv and site.csv perhaps we could make that the first selection on the geolocation page https://architecturasinica-dev.app.vanderbilt.edu/exist/apps/tcadrt/geolocation.html?

**Comment by wsalesky** [comment]
@millertg Do you mean something different from the date slider?

**Comment by millertg** [comment]
I am not sure from where the dates of the buildings are being pulled. For example, the Nanshentou Erxian temple mistakenly has two dates associated with it: a Jin dynasty date on the site.csv and a Song dynasty date on the building.csv (yes, I have fixed this :-)). On the date slider the complex comes up under Northern Song dates, so it is pulling from the building.csv and the site.csv. Consequently you can have a result on the date slider that contradicts the text that come up dynasty complex/building come up when you want to narrow your range, here is an example for the date slider. 
https://architecturasinica-dev.app.vanderbilt.edu/exist/apps/tcadrt/geolocation.html?fq=;fq-Dynasty:Jin&endDate=1084-12-14&startDate=0900-08-01
One thing that could help might be an "or" rather than the "&" in the slider function

But it would be nice to be able to have a separate search for building(s)/artifact(s), that won't include the dates for the larger complex.

**Comment by wsalesky** [comment]
Okay, so the date slider should not be using the Dynasty dates on buildings, just on sites is that correct?

**Comment by millertg** [comment]
Would it be a strange to have 2 date sliders? One for sites  and one for buildings?

tm

Sent from my iPhone

On Mar 17, 2018, at 9:14 AM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, so the date slider should not be using the Dynasty dates on buildings, just on sites is that correct?

**Comment by millertg** [comment]
Hi Winona,
I updated the building.csv, and made some changes to the site.csv. I will still need to do some more research to verify earliest dates for all of the sites, but if we could update the buildings, that would be great.

Thanks so much-
Tracy

On Mar 17, 2018, at 9:14 AM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, so the date slider should not be using the Dynasty dates on buildings, just on sites is that correct?

**Comment by millertg** [comment]
Hi Winona,
I was able to update the dates on the building.csv, and correct some mistakes on the site.csv. I need to so more research on the sites to get the result I want. Previously I had focused only on extant buildings, but I think, looking at it on-line, I should include the textual history of the site as we know it, and then have each of the artifacts listed separately in the building(s)/artifact(s) category. That will allow for different types of information to be available to different kinds of users and/or research questions.

So, it would be nice to see a data update whenever you have time to run it, just so I can see what I have to deal with next.

Thanks!

Tracy

**Comment by wsalesky** [comment]
I updated the data. Let me know if this is looking better.

**Comment by millertg** [comment]
It does look much better. It seems something is strange with the Liao and Jin dynasties, however. Liao comes up as a url, and one site (Shanhua Monastery) that has both Liao and Jin structures still reads Jin when I narrow the dates to pre-Jin: 
https://architecturasinica-dev.app.vanderbilt.edu/exist/apps/tcadrt/research-tool.html?fq=;fq-Dynasty:http://architecturasinica.org/keyword/Liao-&endDate=1076-01-28&startDate=0035-01-02
![screen shot 2018-03-18 at 3 04 59 pm](https://user-images.githubusercontent.com/25234059/37570469-3571b94a-2abe-11e8-8d2d-e4b1531560e1.png)

**Comment by wsalesky** [comment]
@millertg The way the Dynasty filter works in the data is that each place tagged with the that dynasty gets a tei:relation linking it to the matching dynasty. 

Here is an example: 
The building dates are encoded like here, these dates are used by the date range slider: 
https://github.com/VandyVRC/tcadrt/blob/tcadrt-dev/data/places/buildings/tei/000124.xml#L80

Then the relationship to the dynasty is coded here: 
https://github.com/VandyVRC/tcadrt/blob/tcadrt-dev/data/places/buildings/tei/000124.xml#L121

Each dynasty has its own record which I can pull the name for the filter from. However, in some cases the csv data does not match a name in the dynasties.xml file, that is when we get the URL instead of a label. So we just need to clean up the data, or resolve some of the question marks and that should help. One place where I noticed this structure will fail is when a site spans multiple dynasties using a '-', my script will then only grab the beginning and ending dynasty. It is hard to script this correctly, but we can discuss options.

**Comment by millertg** [comment]
I am not sure I completely understand, but it looks like you are pulling the date from the building.csv and then converting it into a dynasty name based on our list. Is that right?

On Mar 19, 2018, at 9:11 AM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


@millertg<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmillertg&data=02%7C01%7Ctracy.g.miller%40vanderbilt.edu%7Ccd0a3de7e0014920ac0608d58da3484c%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636570654789531335&sdata=zEhisceMXBVt0YXt0TwM5%2Fc69qjlX7QjB8PnyQxYeLs%3D&reserved=0> The way the Dynasty filter works in the data is that each place tagged with the that dynasty gets a tei:relation linking it to the matching dynasty.

Here is an example:
The building dates are encoded like here, these dates are used by the date range slider:
https://github.com/VandyVRC/tcadrt/blob/tcadrt-dev/data/places/buildings/tei/000124.xml#L80<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVandyVRC%2Ftcadrt%2Fblob%2Ftcadrt-dev%2Fdata%2Fplaces%2Fbuildings%2Ftei%2F000124.xml%23L80&data=02%7C01%7Ctracy.g.miller%40vanderbilt.edu%7Ccd0a3de7e0014920ac0608d58da3484c%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636570654789531335&sdata=gDc3earH%2FXbIbQ3wHgEn8djX2mxwvepOK0odms7xC2k%3D&reserved=0>

Then the relationship to the dynasty is coded here:
https://github.com/VandyVRC/tcadrt/blob/tcadrt-dev/data/places/buildings/tei/000124.xml#L121<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVandyVRC%2Ftcadrt%2Fblob%2Ftcadrt-dev%2Fdata%2Fplaces%2Fbuildings%2Ftei%2F000124.xml%23L121&data=02%7C01%7Ctracy.g.miller%40vanderbilt.edu%7Ccd0a3de7e0014920ac0608d58da3484c%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636570654789531335&sdata=IgUe%2F9Un%2FB4eMI%2FFidh89ZmlAyZinYW62EWcuoWk4Ck%3D&reserved=0>

Each dynasty has its own record which I can pull the name for the filter from. However, in some cases the csv data does not match a name in the dynasties.xml file, that is when we get the URL instead of a label. So we just need to clean up the data, or resolve some of the question marks and that should help. One place where I noticed this structure will fail is when a site spans multiple dynasties using a '-', my script will then only grab the beginning and ending dynasty. It is hard to script this correctly, but we can discuss options.

**Comment by wsalesky** [comment]
@millertg Yes, I'm trying to match them. The funky URI's appear when they can not be programmatically matched to anything in that dynast.xml file.

**Comment by millertg** [comment]
Hmm, this is hard because some of the dynasties are co-temporaneous. I think we will need to pull the dynasty names from the site and building records themselves. Maybe the date of the dynasty from the xml file could follow the name of the dynasty in parenthesis.

Date of building/artifact: 1138 [this would be the numerical date from the building.csv)
Dynasty: Dynasty Name (111-222) [this would be the dynasty name from the building.csv with the numerical range pulled from the dynasty xml]

Is that too clumsy?


On Mar 19, 2018, at 10:34 AM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


@millertg<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmillertg&data=02%7C01%7Ctracy.g.miller%40vanderbilt.edu%7C49e8233fafbb4f4c28eb08d58daef898%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636570704989618203&sdata=kQq8sAqGdIb%2FtTKEOS8KaBGqfjSbRpnKYGJ84q0CUok%3D&reserved=0> Yes, I'm trying to match them. The funky URI's appear when they can not be programmatically matched to anything in that dynast.xml file.

**Comment by millertg** [comment]
Also, in columns v and w of the building.csv the numerical beginning and end dates are separated. Can you use those columns so you don't have to deal with the '-'?

**Comment by wsalesky** [comment]
@millertg We can do that. The only problem comes in when trying to use those filters, if you do not explicitly link to each dynasty in someway, the correct buildings and sites will not show up under the dynasty filter. We could eliminate the dynasty filter and just use the date slider if this gets to complicated. The best would of course to be able to include both, but I'm not sure it can happen programmatically, it would involve hand editing the TEI.

**Comment by millertg** [comment]
I think I am still confused. The specific dynasty name for each building is in the spreadsheet, right? I am not sure why it would need to be filtered. Sorry to have to keep asking about this….

On Mar 19, 2018, at 10:59 AM, Winona Salesky <notifications@github.com<mailto:notifications@github.com>> wrote:


@millertg<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmillertg&data=02%7C01%7Ctracy.g.miller%40vanderbilt.edu%7Ccbffce4ae3e54f8c695908d58db272eb%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636570719926454263&sdata=9zrC%2FtmcUScCf5lsRFmPqSMsaRnv8xO%2BBm5ZiHkMRoA%3D&reserved=0> We can do that. The only problem comes in when trying to use those filters, if you do not explicitly link to each dynasty in someway, the correct buildings and sites will not show up under the dynasty filter. We could eliminate the dynasty filter and just use the date slider if this gets to complicated. The best would of course to be able to include both, but I'm not sure it can happen programmatically, it would involve hand editing the TEI.
